---
DNS1:
  192.168.1.1
persistentVolumeClaim:
  enabled: true
serviceWeb:
  http:
    enabled: true
    port: 8084  # Change external port here
    nodePort: ""
   type: LoadBalancer  # Change from ClusterIP to LoadBalancer
  externalTrafficPolicy: Local

  loadBalancerIP: "192.168.1.250"  # Set static LoadBalancer IP
  loadBalancerIPv6: ""

  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc  # Enable shared IP for MetalLB

serviceDns:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
