server:
  persistentVolume:
    enabled: true
    size: 10Gi
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.251
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus-svc

alertmanager:
  persistentVolume:
    enabled: true
    size: 5Gi
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.251
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus-svc
