hostname: "rancher.home.io"  # Replace with your domain
bootstrapPassword: "admin"  # Change this
webhook:
  enabled: false
ingress:
  enabled: true
  tls:
    source: secret
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.205
  externalIPs: []
  # Use the custom IP from the MetalLB range
replicas: 1

