secrets:
  cf-token:
    file: ./cf-token

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "81:80"
      - "443:443"
      - "8082:8080"
    volumes:
      - /var/run/podman/podman.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    

networks:
  proxy:
    external: true
