apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  discord-token: {{ .Values.secrets.discordToken | b64enc | quote }}
  youtube-api-key: {{ .Values.secrets.youtubeApiKey | b64enc | quote }}
  spotify-client-id: {{ .Values.secrets.spotifyClientId | b64enc | quote }}
  spotify-client-secret: {{ .Values.secrets.spotifyClientSecret | b64enc | quote }}
